app:
    resource: "@AppBundle/Controller/"
    type:     annotation

nines_user:
    resource: "@NinesUserBundle/Controller/"
    type: annotation

nines_editor:
    resource: "@NinesEditorBundle/Controller/"
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
